#!/usr/bin/env ruby

class String
  def camel_case_lower
    self.split('_').inject([]){ |buffer,e| buffer.push(buffer.empty? ? e : e.capitalize) }.join
  end
end

def generated_vars
  templates_path = "Sources/XCTestHTMLReport/HTML"
  templates = Dir["#{templates_path}/**/*.html"]

  css_content = File.read("#{templates_path}/style.css").gsub("\"", "\\\"")
  js_content = File.read("#{templates_path}/app.js").gsub("\"", "\\\"")

  templates.map do |template|
    name = File.basename(template, ".*").camel_case_lower
    content = File.read(template)
      .gsub("\"", "\\\"")
      .gsub("/**** CSS ****/", css_content)
      .gsub("/**** JS ****/", js_content)
      .chomp
<<-eos
  static let #{name} = \"\"\"
#{content}
  \"\"\"
eos
  end
end

generated_content = <<-eos

/// DO NOT EDIT! This file is autogenerated by create_templates.rb

struct HTMLTemplates
{
  #{generated_vars.join("\n")}
}

eos

File.open("Sources/XCTestHTMLReport/Classes/HTMLTemplates.swift", "w") { |file| file.puts generated_content }
